---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.0.9
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'tf-checks-prefx_list-example / Evaluate Terraform versions (1.5.0, ./_example/prefix_list/)'
...
