name: tf-checks
permissions:
  id-token: write
on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  tf-checks-basic-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'
      provider: 'aws'
      enable_plan: 'true'
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  tf-checks-complete-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: 'aws'
      enable_plan: 'true'
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  tf-checks-only_rules-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/only_rules/'
      provider: 'aws'
      enable_plan: 'true'
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  tf-checks-prefx_list-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
       working_directory: './examples/prefix_list/'
       provider: 'aws'
       enable_plan: 'true'
       show_plan: false 
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
